<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RMA Request Form</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>RMA Request Form</h1>
        <p class="subtitle">Please fill out the form below to initiate the RMA process.</p>
        
        <form action="submit_rma.php" method="post" enctype="multipart/form-data">
            <label for="full_name">Full Name:</label>
            <input type="text" id="full_name" name="full_name" required>
            
            <label for="email">Email Address:</label>
            <input type="email" id="email" name="email" required>
            
            <label for="order_number">Order Number:</label>
            <input type="text" id="order_number" name="order_number" required>
            
            <label for="product_name">Product Name/Description:</label>
            <input type="text" id="product_name" name="product_name" required>
            
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" required>
            
            <label for="reason">Reason for Return:</label>
            <select id="reason" name="reason" required>
                <option value="defective">Defective Product</option>
                <option value="wrong_item">Wrong Item Received</option>
                <option value="changed_mind">Changed My Mind</option>
                <option value="other">Other</option>
            </select>
            
            <label for="return_type">Return Type:</label>
            <select id="return_type" name="return_type" required>
                <option value="refund">Refund</option>
                <option value="replacement">Replacement</option>
                <option value="repair">Repair</option>
            </select>
            
            <label for="additional_details">Additional Details:</label>
            <textarea id="additional_details" name="additional_details"></textarea>
            
            <label for="attachment">Attach Files:</label>
            <input type="file" id="attachment" name="attachment">
            
            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>
